export const ERROR_DEFINITIONS = {
  // --- VALIDATION (HTTP 400: Bad Request) ---
  REQUIRED: { reason: 'REQUIRED', description: 'Field is mandatory.' },
  EMPTY: { reason: 'EMPTY', description: 'Field cannot be empty.' },
  ARRAY_MIN_SIZE: { reason: 'ARRAY_MIN_SIZE', description: 'Value must be an array and contain at least {min} item(s).' },
  ARRAY_MAX_SIZE: { reason: 'ARRAY_MAX_SIZE', description: 'Value must be an array and contain at most {max} item(s).' },
  MIN_LENGTH: { reason: 'MIN_LENGTH', description: 'Input is below minimum length.' },
  MAX_LENGTH: { reason: 'MAX_LENGTH', description: 'Input exceeds maximum length.' },
  INVALID: { reason: 'INVALID', description: 'Invalid input format.' },
  INVALID_UUID: { reason: 'INVALID_UUID', description: 'Value must be a valid UUID v4.' },
  INVALID_INTEGER: { reason: 'INVALID_INTEGER', description: 'Value must be an integer.' },
  INVALID_STRING: { reason: 'INVALID_STRING', description: 'Value must be a string.' },
  INVALID_BOOLEAN: { reason: 'INVALID_BOOLEAN', description: 'Value must be a boolean.' },
  INVALID_ARRAY: { reason: 'INVALID_ARRAY', description: 'Value must be an array.' },
  INVALID_OBJECT: { reason: 'INVALID_OBJECT', description: 'Value must be an object.' },
  INVALID_DATE: { reason: 'INVALID_DATE', description: 'Value must be a date.' },
  INVALID_BASE64: { reason: 'INVALID_BASE64', description: 'Value must be a valid base64 string.' },
  INVALID_PUMP_NO: { reason: 'INVALID_PUMP_NO', description: 'Value must start with "#" followed by a number.' },
  INVALID_FISCAL_ID: { reason: 'INVALID_FISCAL_ID', description: 'Value must be a valid fiscal ID.' },
  INVALID_ENUM: { reason: 'INVALID_ENUM', description: 'Value must be a valid enum.' },

  // --- AUTH (HTTP 401/403: Security) ---
  UNAUTHORIZED: { reason: 'UNAUTHORIZED', description: 'Authentication required.' },
  FORBIDDEN: { reason: 'FORBIDDEN', description: 'Access denied.' },

  // --- BASKET (HTTP 422: Domain Specific Logic) ---
  BASKET_DELETED: { reason: 'BASKET_DELETED', description: 'Basket is deleted and cannot be used.' },
  BASKET_COMPLETED: { reason: 'BASKET_COMPLETED', description: 'Basket is already completed.' },
  BASKET_PAID: { reason: 'BASKET_PAID', description: 'Basket payment has already been processed.' },
  BASKET_LOCKED: { reason: 'BASKET_LOCKED', description: 'Basket is locked and currently in use by another device.' },
  BASKET_NOT_LOCKED: { reason: 'BASKET_NOT_LOCKED', description: 'Basket is not locked and cannot be unlocked.' },
  BASKET_FULL: { reason: 'BASKET_FULL', description: 'Basket has reached the item limit.' },
  BASKET_PAYMENT_DETAILS_MISSING: { reason: 'BASKET_PAYMENT_DETAILS_MISSING', description: 'Both payment items and payment slips are required to complete the basket.' },
  BASKET_PAYMENT_DETAILS_NOT_ALLOWED: { reason: 'BASKET_PAYMENT_DETAILS_NOT_ALLOWED', description: 'Payment items and payment slips are not allowed to be set after the basket is paid.' },

  // --- SYSTEM (HTTP 404/409/500: Infrastructure) ---
  FOREIGN_KEY_VIOLATION: { reason: 'FOREIGN_KEY_VIOLATION', description: 'Foreign key violation.' },
  NOT_NULL_VIOLATION: { reason: 'NOT_NULL_VIOLATION', description: 'Not null violation.' },
  CHECK_VIOLATION: { reason: 'CHECK_VIOLATION', description: 'Check violation.' },
  INVALID_TEXT_REPRESENTATION: { reason: 'INVALID_TEXT_REPRESENTATION', description: 'Invalid text representation.' },
  NOT_FOUND: { reason: 'NOT_FOUND', description: 'Resource not found.' },
  ROUTE_NOT_FOUND: { reason: 'ROUTE_NOT_FOUND', description: 'Route not found.' },
  ALREADY_EXISTS: { reason: 'ALREADY_EXISTS', description: 'Record already exists.' },
  DATABASE_ERROR: { reason: 'DATABASE_ERROR', description: 'Database integrity error.' },
  INTERNAL_SERVER_ERROR: { reason: 'INTERNAL_SERVER_ERROR', description: 'Unexpected internal server error.' },
  FAILED_DEPENDENCY: { reason: 'FAILED_DEPENDENCY', description: 'External service is unreachable.' },
  METHOD_NOT_ALLOWED: { reason: 'METHOD_NOT_ALLOWED', description: 'Method not allowed.' },
  TRANSACTION_MANAGER_NOT_INITIALIZED: { reason: 'TRANSACTION_MANAGER_NOT_INITIALIZED', description: 'Transaction manager not initialized.' },
  PACKAGE_JSON_NOT_FOUND: { reason: 'PACKAGE_JSON_NOT_FOUND', description: 'package.json not found.' },
  DATA_SOURCE_NOT_INITIALIZED: { reason: 'DATA_SOURCE_NOT_INITIALIZED', description: 'Data source not initialized.' },
  TEST_CONTEXT_NOT_INITIALIZED: { reason: 'TEST_CONTEXT_NOT_INITIALIZED', description: 'Test context not initialized.' },
  TERMINALS_NOT_FOUND: { reason: 'TERMINALS_NOT_FOUND', description: 'Terminals not found.' },
  TERMINAL_NOT_FOUND: { reason: 'TERMINAL_NOT_FOUND', description: 'Terminal not found.' },
  BRANCH_NOT_FOUND: { reason: 'BRANCH_NOT_FOUND', description: 'Branch not found.' },
  MERCHANT_NOT_FOUND: { reason: 'MERCHANT_NOT_FOUND', description: 'Merchant not found.' },
  DISTRIBUTION_COMPANY_NOT_FOUND: { reason: 'DISTRIBUTION_COMPANY_NOT_FOUND', description: 'Distribution company not found.' },
  ORGANIZATION_NOT_FOUND: { reason: 'ORGANIZATION_NOT_FOUND', description: 'Organization not found.' },
  SERVICE_NOT_SUPPORTED: { reason: 'SERVICE_NOT_SUPPORTED', description: 'Service not supported.' },
  SERVICE_NOT_FOUND: { reason: 'SERVICE_NOT_FOUND', description: 'Service not found.' },
  FILE_NOT_FOUND: { reason: 'FILE_NOT_FOUND', description: 'File not found: {filepath}' },
  ORGANIZATION_HEADERS_NOT_FOUND: { reason: 'ORGANIZATION_HEADERS_NOT_FOUND', description: 'Organization headers not found.' },
};
